### ISSUE TITLE
Failed to load phpMyAdmin configuration

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry-community/phpmyadmin-cf#1]
After running instructions from README got following error while trying to access phpMyAdmin web interface:

```
phpMyAdmin - Error
Failed to load phpMyAdmin configuration (./config.inc.php:30): Class 'CfCommunity\CfHelper\CfHelper' not found
```

OSS CF v192

**Comment by lexsys27** [comment]
This helps:

added to `manifest.yml`

```
buildpack: https://github.com/cloudfoundry/php-buildpack.git
```

**Comment by ArthurHlt** [comment]
Well yeah your Cloud Foundry instance was released in November 6th, 2014 (see: https://github.com/cloudfoundry-community/cf-docs-contrib/wiki/All-CF-Releases ) and the new and official php-buildpack came on December.
